version: '3'

networks:
  zapper-data:
    driver: bridge

volumes:
  mongo-data:
    driver: local

services:
  zapper-app:
    build:
      context: .
    container_name: zapper-app
    ports:
      - "3000:3000"
    networks:
      - zapper-data
    depends_on:
      - zapper-mongo
    volumes:
      - .:/app      # Mount the app code into the container
      - /app/node_modules # Avoid overwriting node_modules in the container
    command: npm start

  zapper-mongo:
    image: mongo:latest
    container_name: zapper-mongo
    ports:
      - "27017:27017"
    networks:
      - zapper-data
    volumes:
      - mongo-data:/data/db
